[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shared-timeout-requests"
version = "0.0.1"
requires-python = ">= 3.8"
dependencies = [
    "typing-extensions>=3.10.0",
    "requests>=0.3.3"
]
